name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-and-start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and start backend
        working-directory: backend
        run: |
          npm install
          npm start &
          sleep 10
          echo "✅ Backend started"

      - name: Install and start frontend
        working-directory: frontend
        run: |
          npm install
          npm start &
          sleep 10
          echo "✅ Frontend started"
